### PR TITLE
:memo: Docs for common snippet duplicate key issue

### PR DESCRIPTION
**Pull request by benogle**
This is a common issue, let's help people make this mistake less. https://github.com/atom/atom/issues/2695#issuecomment-125680992

### CODE REVIEW

**Comment by izuzak** [comment]
Also see https://github.com/atom/docs/pull/100, opened earlier today. I think we can combine these two.

**Comment by benogle** [comment]
Ah, I should have paid attention

**Comment by benogle** [comment]
I'm ok closing this if you guys dont think it's necessary

**Comment by izuzak** [comment]
I think we can close this one, but I'd love it if #100 had specific examples like this PR does. @mnquintana how do you feel about merging the examples from this PR into #100?

**Comment by mnquintana** [comment]
Sure, sounds good - do you think they should go into the snippets section or into Configuring with CSON?

**Comment by izuzak** [comment]
> do you think they should go into the snippets section or into Configuring with CSON?

I think both would be okay, but I'd vote for putting it into the general Configuring with CSON section.

**Pull request closed without merging**
