### PR TITLE
Move build system to Nanoc

### PR DESCRIPTION
**Pull request by gjtorikian**
This PR is a proposal to move the build system off of the proprietary, closed-source implementation of [Atlas](https://atlas.oreilly.com/) to the static-site generator [Nanoc](http://nanoc.ws/). 

A reason for making this change is that Atlas is a huge black box. It's virtually impossible for anyone interested in making contributions to the content here to generate documentation locally that matches the online environment. Beyond that, there are numerous bugs, such as:

* [Links not working](https://cloud.githubusercontent.com/assets/64050/8733339/559a4ba4-2bb8-11e5-879b-57feade3caa7.gif)
* [Inconsistent titles](https://cloud.githubusercontent.com/assets/64050/8733317/3dc733f2-2bb8-11e5-9791-b78ea96b4656.png)
* [Broken version switcher](https://cloud.githubusercontent.com/assets/64050/8733338/559a3484-2bb8-11e5-8560-f9ec6ab41608.gif)

This PR:

* Implements a Nanoc build system. Asciidoctor is still the primary markup format.
* Rearranges the directories so that they make sense for Nanoc. (Everything needs to be under a *content* folder.)
* Removes various Atlas assets and stylesheets that are unused.
* Sets up build tools and scripts to generate the docs. (`script/bootstrap` to fetch dependencies, `script/server` to start the docs locally, etc.)
* Adds a CI via [html-proofer](https://github.com/gjtorikian/html-proofer) to ensure that no links are broken.

The one thing we lose with this switch is the ability for multiple outputs (currently HTML, PDF, Mobi, eBook). We've been tracking usages for all of these formats since July 2015, and there's virtually no one using Mobi or eBook. PDF has some usage, but it's still rather small compared to the overwhelming majority of HTML. Therefore, I think it's more appropriate to fix the immediate problem of allowing people to generate the docs locally. We should circle back to PDF generation [via pandoc](https://github.com/jgm/pandoc) in the future.

Good docs are an important tool to help newcomers understand, contribute to, and make use of a project. I hope that by simplifying the build system here we'll see more content updates, as the mystery of how it all works should be eliminated.

/cc @thedaniel @izuzak @lee-dohm 

Not sure who else to cc!

### CODE REVIEW

**Comment by gjtorikian** [comment]
Forgot to mention that Atlas is also being deprecated by O'Reilly: https://github.com/atom/docs/issues/140

**Comment by lee-dohm** [comment]
:heart_eyes_cat:

/cc @atom/feedback

**Comment by gjtorikian** [comment]
*Bump*

**Comment by lee-dohm** [comment]
I'll take some time tonight and resolve the conflicts to keep this up-to-date.

**Comment by thedaniel** [comment]
This is on my hit list for next week.

**Comment by thedaniel** [comment]
`script/bootstrap` fails for me, which is not a great start, however I will figure out what's going on there and give this a good review with the intention of landing it asap and moving doc generation and hosting out of the rails app this week.

**Comment by thedaniel** [comment]
@gjtorikian It's been a few months since we talked about this in person. Can you refresh my memory / record here what we decided for deployment and search? My recollection was that we were going to serve this separate from the atom.io webapp e.g. on a subdomain, provide 301s from the current docs, and use client-side search much like https://help.github.com/ - does that sound right?

**Comment by thedaniel** [comment]
Also, [this commit](https://github.com/atom/docs/commit/142d15d623b299302642bd86b315c3ad444c2280) implies there might be some things missing still.. is there a checklist somewhere? If it's nuanced we can do some synchronous communication and I can transcribe it here later.

**Comment by gjtorikian** [comment]
> Can you refresh my memory / record here what we decided for deployment and search? My recollection was that we were going to serve this separate from the atom.io webapp e.g. on a subdomain, provide 301s from the current docs, and use client-side search much like https://help.github.com/ - does that sound right?

I don't remember what we decided for deployment. I think you're right, though. We could shove this over to GitHub Pages and call it `flight-manual.atom.io`. Search was definitely going to be client-based, using [lunr.js](http://lunrjs.com/) as a system. I think we had also talked about just tweaking the deployment/indexing process to get this into atom.io/docs as normal but I don't think we were really settled on it.

**Comment by thedaniel** [comment]
@simurai do you have some time to get this running and style the search autocomplete popup and the search results page? It doesn't necessarily have to be a pixel-for-pixel clone of what's on atom.io now, but I just borrowed some styles from help.github.com and they don't quite fit.

Also, if you need to add scss files to subdirectories like `shared/` you'll also have to add an `@import` to the file with the same name (e.g. `_shared.scss`) since this doesn't have some of the nice helpers from the rails asset pipeline.

**Comment by simurai** [comment]
@thedaniel FYI: Tried to run `script/bootstrap`, but I got

```bash
==> Installing gem dependencies…
script/bootstrap: line 11: bundle: command not found
script/bootstrap: line 12: bundle: command not found
```

So StackOverflow said to `gem install bundler` and after `script/bootstrap` seemed to work.

Should we add that to the `README.md`? And maybe also mention to open `http://localhost:4000`. Or is that clear for everyone?

**Comment by simurai** [comment]
@thedaniel Ok, it's now a bit closer to atom.io. Except the search results page, but are we even keeping it, now that there is the autocomplete?

Here a couple other improvements I found:

- [ ] Add keyboard navigation for the autocomplete.
- [ ] Sometimes the autocomplete results show double?
- [ ] Chapter pages have the whole toc at the top: [img](https://cloud.githubusercontent.com/assets/378023/13696826/50b7ccdc-e7ac-11e5-8ee7-0e19a101a966.png)
- [ ] All chapter summaries get selected, not just the one you click on.
- [ ] No syntax highlighting

**Comment by thedaniel** [comment]
I saw the autocomplete results showing double - seems like that element isn't getting emptied out when it updates, should be an easy fix.

**Comment by lee-dohm** [comment]
I'd prefer if we had some sort of search results page. Often search results pages allow one to walk through things when you don't know what you're searching for. Whereas autocomplete is better for when you do, you just don't want to have to type the whole thing.

**Comment by simurai** [comment]
> @lee-dohm I'd prefer if we had some sort of search results page.

Ok, it's now styled too.

Something that is a bit weird: The result page updates while typing, like autocomplete, just not as fast. Maybe that can be disabled.

**Comment by thedaniel** [comment]
It would be nice to have section pages render TOCs in the markdown, like in the old layout.

**Comment by lee-dohm** [comment]
`ul` font size appears too large:

http://flight-manual.atom.io/using-atom/sections/basic-customization/

screen shot 2016-03-14 at 11 09 45 am

**Comment by gjtorikian** [comment]
> It would be nice to have section pages render TOCs in the markdown, like in the old layout.

Not sure I follow. Could you show me?

**Comment by thedaniel** [comment]
I realized I was imagining things and just removed their anchor tags in the following commit :) I had thought I recalled section summaries having links to their items but couldn't find it on atom.io after all. 

--
https://github.com/thedaniel




On Mon, Mar 14, 2016 at 11:12 AM -0700, "Garen Torikian" <notifications@github.com> wrote:













It would be nice to have section pages render TOCs in the markdown, like in the old layout.




Not sure I follow. Could you show me?

**Comment by simurai** [comment]
Question: If you click on "Documentation" form http://flight-manual.atom.io/, should it got to https://atom.io/docs? That page will stay as is, right?

**Comment by gjtorikian** [comment]
Yeah, I think that link can stay the same.

**Comment by simurai** [comment]
> @lee-dohm `ul` font size appears too large:

Should be fixed. Now also shows bullets:

screen shot 2016-03-15 at 11 52 07 am

**Comment by thedaniel** [comment]
I think it's time to hit the merge button.

**Pull request merged**
