### PR TITLE
Updates Atom Packages section to match 1.0 changes

### PR DESCRIPTION
**Pull request by eebs**
I updated the screenshots so that there wouldn't be any confusion between the wording saying one thing and the screenshots showing something else. If the screenshots need to be changed to match some standardization, just give me a shout.

### CODE REVIEW

**Comment by simurai** [comment]
@eebs Updated the screenshots a bit -> https://github.com/eebs/atom-docs/pull/1 but otherwise :+1:

**Comment by eebs** [comment]
Awesome thanks, merged the updated screenshots in.

**Comment by izuzak** [comment]
@eebs Thanks for doing this. :zap: Just looking at some of the screenshots that are updated in this PR -- I think some (all?) might not need to be updated, by just renamed? So, for example, `book/02-using-atom/images/package-settings.png` is renamed to `book/02-using-atom/images/package-specific-settings.png` but also updated. However, that image was also updated in https://github.com/atom/docs/pull/90 which you merged into this PR, and the update in this PR doesn't seem like it adds value. (Current version of that image is [here](https://github.com/atom/docs/blob/13b163201812b87f8423b5973972660d6aaca2da/book/03-hacking-atom/images/package-settings.png) and the image from this PR is [here](https://github.com/eebs/atom-docs/blob/atom-packages/book/02-using-atom/images/package-specific-settings.png)). Just wanted to make sure these updates to the screenshots were intentional and still needed after #90 was merged.

**Comment by izuzak** [comment]
Nope, I was wrong -- that image was not updated in #90. The image updated in this PR is 

`02-using-atom/images/package-specific-settings.png`

and the image updated in #90 is:

`03-hacking-atom/images/package-settings.png`.

Sorry about that, didn't pay close attention to the filenames.

**Comment by izuzak** [comment]
Thanks again for this :bow:

**Comment by eebs** [comment]
Happy to help, cheers!

**Pull request merged**
