### PR TITLE
Fixes pane title in Atom Packages section

### PR DESCRIPTION
**Pull request by eebs**

### CODE REVIEW

**Comment by eebs** [comment]
Just noticed some additional out of date language, and the screen shots are out of date as well. I'll work on updating these too.

**Comment by mnquintana** [comment]
Were you gonna do those in this PR? It'd probably be best to do a separate PR. Also, I'd hold off on screenshots for now - we definitely need to update them, but we're still working out standards for them. Thanks for doing this though!

**Comment by eebs** [comment]
I was going to add them to this PR, but I could open a new one instead. I'm hesitant to update the wording without the screenshots, as they would no longer match. What's your preference?

**Comment by eebs** [comment]
Closing, opened #84 instead.

**Pull request closed without merging**
